apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
  labels:
    name: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp-frontend
        image: smehta26/pyweb:1.0
        ports:
        - containerPort: 5000
      - name: webapp-redis
        image: redis:alpine
