apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command:
    - "/bin/sh"
    - "-c"
    - "env"
    env:
    - name: LEVEL_HOW 
      valueFrom:
        configMapKeyRef:
          name: my-config-map 
          key: how
    - name: LEVEL_TYPE
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: type 
  restartPolicy: Never

