apiVersion: v1
kind: Pod 
metadata:
  name: security-context-demo
spec:
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: security-context-demo
---

apiVersion: v1
kind: Pod 
metadata:
  name: security-context-demo1
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: security-context-demo1
    securityContext:
      allowPrivilegeEscalation: false  
---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo2
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: security-context-demo2
    securityContext:
      runAsUser: 1000
