apiVersion: batch/v1
kind: CronJob 
metadata:
  name: hello
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: countdown
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - "/bin/sh"
            - "-c"
            - "date; echo Hello from Kubernetes cluster"
          restartPolicy: OnFailure 
