---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness-http-success
  name: liveness-http-success
spec:
  containers:
  - name: liveness-http-success
    image: smehta26/k8s-liveliness
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /health-check
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness-http-fail
  name: liveness-http-fail
spec:
  containers:
  - name: liveness-http-fail
    image: smehta26/k8s-liveliness
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /bad-health
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
