apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: qa
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: demo
  namespace: qa
spec: 
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
status: {}
