apiVersion: v1
kind: Pod 
metadata:
  creationTimestamp: null
  labels:
    run: quota-demo-pod1
  name: quota-demo-pod2
  namespace: qa
spec:
  containers:
  - image: nginx:1.7.9
    name: quota-demo-pod1
    resources: 
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
status: {}
