apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    name: task-pv-pod
spec:
  volumes:
  - name: task-pv-vol
    persistentVolumeClaim:
      claimName: task-pv-claim
  containers:
    - image: nginx:1.7.9
      name: task-pv-container
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pv-vol
---
apiVersion: v1
kind: Service
metadata:
  name: task-pv-pod-service
spec:
  type: LoadBalancer
  selector:
    name: task-pv-pod
  ports:
  - port: 80

