apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment 
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "Version 1.7.9"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        #      - name: nginx
        #image: nginx:1.7.9
      - name: alpine
        image: smehta26/apache:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels: 
    app: nginx-label
spec:
  ports:
  - port: 80
    nodePort: 32032
  selector:
    app: nginx
  type: NodePort
  externalIPs:
  - 167.71.230.213  
    #  type: LoadBalancer
