apiVersion: v1
kind: Pod 
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
  nodeSelector:
    myserver: "true"
--- Before Running
--- k get nodes --show-labels                      
--- k label node minion-2 myserver=true            
--- vi 012-nodeselector/nodeselector.yml           
--- Run with myserver ="false"
--- k apply -f  012-nodeselector/nodeselector.yml  
--- k get pods                                     
--- Update pod definition to use myserver="true"
--- vi 012-nodeselector/nodeselector.yml           
--- k delete -f  012-nodeselector/nodeselector.yml 
--- k apply -f  012-nodeselector/nodeselector.yml  
--- k get pods                                     
